print('1 - Mateus')
print('2 - Tiago ')
print('3 - Nicole')
input('Escolha a pessoa')
print('1 - Python')
print('2 - Java  ')
print('3 - PHP')
input('Escolha a Linguagem')
print('1 - React')
print('2 - Angular  ')
print('3 - Vue')
input('Escolha a Framework Front')
print('1 - MsSqlServer')
print('2 - PostgreSQL  ')
print('3 - MongoDb')
input('Escolha a Banco')
print('Validando regras....')
print('Errou mizeravi')
